export const COUNTER = {
  VISITOR_COUNT: 'VISITOR_COUNT',
  AIP_NUMBER: 'AIP_NUMBER',
  SCHOOL_NEED_CODE: 'SCHOOL_NEED_CODE',
  SHS_IMMERSION_CODE: 'SHS_IMMERSION_CODE',
  CLUSTER_CODE: 'CLUSTER_CODE',
};
