export const PROVIDER = {
  TENANT_CONNECTION: 'TENANT_CONNECTION',
  USER_MODEL: 'USER_MODEL',
  TENANT_MODEL: 'TENANT_MODEL',
  AIP_MODEL: 'AIP_MODEL',
  SCHOOL_MODEL: 'SCHOOL_MODEL',
  SCHOOL_NEED_MODEL: 'SCHOOL_NEED_MODEL',
  IMAGE_UPLOAD_MODEL: 'IMAGE_UPLOAD_MODEL',
  CLUSTER_MODEL: 'CLUSTER_MODEL',
};
