export enum Region {
  Region1 = 'Region1',
  Region2 = 'Region2',
  Region3 = 'Region3',
  Region4A = 'Region4A',
  Region4B = 'Region4B',
  Region5 = 'Region5',
  Region6 = 'Region6',
  Region7 = 'Region7',
  Region8 = 'Region8',
  Region9 = 'Region9',
  Region10 = 'Region10',
  Region11 = 'Region XI',
  Region12 = 'Region XII',
  Region13 = 'Region13',
  NCR = 'NCR',
  CAR = 'CAR',
  BARMM = 'BARMM',
}
